create database scenario;

create table if not exists scenario.SCENARIO
(
  ID            INT AUTO_INCREMENT,
  NAME          VARCHAR(255),
  AUTHOR        VARCHAR(255),
  CREATION_DATE DATETIME,
  PRIMARY KEY (ID)
);

create table if not exists scenario.SCENARIO_ACTION_STEP
(
  ID           INT AUTO_INCREMENT,
  SCENARIO_ID  INT,
  TRIGGER_TIME INT,
  ACTION       VARCHAR(255),
  PRIMARY KEY (ID),
  FOREIGN KEY (SCENARIO_ID)
    REFERENCES SCENARIO (ID)
    ON DELETE CASCADE
);

create table if not exists scenario.SCENARIO_CREATE_TRAIN_STEP
(
  ID            INT AUTO_INCREMENT,
  SCENARIO_ID   INT,
  TRIGGER_TIME  INT,
  TRAIN_NUMBER  VARCHAR(255),
  MOVEMENT_LINE VARCHAR(255),
  PRIMARY KEY (ID),
  FOREIGN KEY (SCENARIO_ID)
    REFERENCES SCENARIO (ID)
    ON DELETE CASCADE
);
